version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
  pdftohtml:
    image: pavanreddi123/pdf2htmlex
    container_name: pdftohtml
    ports:
      - '4000:4000'
    restart: always
networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
